numero1 = prompt ('Ingrese cuál es el numero 1:')
numero2 = prompt ('Ingrese cuál es el numero 2:')

var resultadoSuma = parseFloat(numero1) + parseFloat(numero2)
var resultadoResta = parseFloat(numero1) - parseFloat(numero2)
var resultadoMultiplicacion = parseFloat(numero1) * parseFloat(numero2)
var resultadoDivision = parseFloat(numero1) / parseFloat(numero2)
var resultadoResiduo = parseFloat(numero1) % parseFloat(numero2)
var resultadoCuadrado = parseFloat(numero1) * parseFloat(numero1)
var resultadoCubo = parseFloat(numero2) * parseFloat(numero2) * parseFloat(numero2)

console.log(' Suma: ' + numero1 + '+' + numero2 + '=' + resultadoSuma)
console.log(' Resta: ' + numero1 + '-' + numero2 + '=' + resultadoResta)
console.log(' Multiplicación: ' + numero1 + '*' + numero2 + '=' + resultadoMultiplicacion)
console.log(' División: ' + numero1 + '/' + numero2 + '=' + resultadoDivision)
console.log(' Residuo: ' + numero1 + '%' + numero2 + '=' + resultadoResiduo)
console.log(' El cuadrado del primer numero: ' + numero1 + '*' + numero1 + '=' + resultadoCuadrado)
console.log(' El cubo del segundo numero: ' + numero2 + '*' + numero2 + '*' + numero2 + '=' + resultadoCubo)

alert(' Suma: ' + numero1 + '+' + numero2 + '=' + resultadoSuma)
alert(' Resta: ' + numero1 + '-' + numero2 + '=' + resultadoResta)
alert(' Multiplicación: ' + numero1 + '*' + numero2 + '=' + resultadoMultiplicacion)
alert(' División: ' + numero1 + '/' + numero2 + '=' + resultadoDivision)
alert(' Residuo: ' + numero1 + '%' + numero2 + '=' + resultadoResiduo)
alert(' El cuadrado del primer numero: ' + numero1 + '*' + numero1 + '=' + resultadoCuadrado)
alert(' El cubo del segundo numero: ' + numero2 + '*' + numero2 + '*' + numero2 + '=' + resultadoCubo)